name: Build and Deploy Documentation

on:
  push:
    branches: [ main, Enhancements-SoftwareEngineeringAndDesign ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          doxygen \
          graphviz \
          cmake \
          ninja-build \
          build-essential \
          clang-15 \
          libc++-15-dev \
          libc++abi-15-dev
        
    - name: Install Python documentation dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docs/requirements.txt
        
    - name: Install Conan
      run: |
        pip install "conan>=2.0"
        conan profile detect --force
        
    - name: Configure Conan profile for CI
      run: |
        conan profile update settings.compiler=clang default
        conan profile update settings.compiler.version=15 default
        conan profile update settings.compiler.libcxx=libc++ default
        conan profile update settings.build_type=Release default
        
    - name: Install Conan dependencies
      run: |
        mkdir build && cd build
        conan install .. --output-folder=. --build=missing -s build_type=Release
        
    - name: Configure CMake
      run: |
        cmake -B build -S . \
          -DCMAKE_TOOLCHAIN_FILE=build/conan_toolchain.cmake \
          -DCMAKE_BUILD_TYPE=Release \
          -DLIARSDICE_BUILD_DOCS=ON \
          -DLIARSDICE_BUILD_TESTS=OFF \
          -DLIARSDICE_BUILD_EXAMPLES=OFF \
          -DLIARSDICE_BUILD_BENCHMARKS=OFF \
          -DCMAKE_CXX_COMPILER=clang++-15 \
          -DCMAKE_C_COMPILER=clang-15
          
    - name: Build documentation
      run: |
        cmake --build build --target docs --parallel
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./build/docs/html

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-docs
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4