name: Documentation

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
    branches: [ main ]

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

permissions:
  contents: write

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev
          pip3 install jinja2 Pygments sphinx sphinx-rtd-theme breathe

      - name: Install Doxygen
        uses: ssciwr/doxygen-install@v1
        with:
          version: "1.10.0"

      - name: Configure and build docs
        run: |
          cmake -S. -Bbuild -DLIARSDICE_BUILD_DOCS=ON -DLIARSDICE_BUILD_TESTS=OFF
          cmake --build build --target GenerateDocs

      - name: Validate Doxygen generation
        run: |
          # Check if Doxygen successfully generated output
          if [ ! -d "build/documentation/doxygen/html" ]; then
            echo "Error: Doxygen HTML output directory not found"
            exit 1
          fi
          
          # Check for main documentation files
          if [ ! -f "build/documentation/doxygen/html/index.html" ]; then
            echo "Error: Main index.html not found"
            exit 1
          fi
          
          # Check for warnings in Doxygen log
          if [ -f "build/documentation/doxygen/doxygen.log" ]; then
            if grep -q "Warning" build/documentation/doxygen/doxygen.log; then
              echo "Doxygen warnings found:"
              grep "Warning" build/documentation/doxygen/doxygen.log
              # Don't fail on warnings for now, just report them
            fi
          fi
          
          echo "Doxygen documentation generated successfully"

      - name: Validate database schema documentation
        run: |
          python3 scripts/validate_database_schema.py || echo "Schema validation skipped (implementation pending)"

      - name: Publish to GitHub Pages
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/documentation/doxygen/html