name: Install

# DEPRECATED: This workflow is now part of the main CI workflow (.github/workflows/ci.yml)
# Only kept for manual testing or specific install debugging

on:
  workflow_dispatch:  # Only manual trigger

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install Boost
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Build and install library
        run: |
          cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release -DLIARSDICE_BUILD_TESTS=OFF -DLIARSDICE_BUILD_EXAMPLES=OFF
          sudo cmake --build build --target install
          rm -rf build

      - name: Configure test with installed version
        run: cmake -Stest -Bbuild -DTEST_INSTALLED_VERSION=1

      - name: Build tests
        run: cmake --build build --config Debug -j4

      - name: Run tests
        run: |
          cd build
          ctest --build-config Debug --output-on-failure