name: Standalone

# DEPRECATED: This workflow is now part of the main CI workflow (.github/workflows/ci.yml)
# Only kept for manual testing or specific standalone debugging

on:
  workflow_dispatch:  # Only manual trigger

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/cpm_modules
            ~/.cache/pip
            ~/Library/Caches/pip
          key: ${{ github.workflow }}-${{ matrix.os }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev ninja-build

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install boost ninja

      - name: Configure
        run: cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build
        run: cmake --build build -j4

      - name: Test executable
        run: |
          ./build/standalone/liarsdice --help
          printf "2\n1\n" | ./build/standalone/liarsdice --seed 12345 || true