name: Style

# This workflow is integrated into the main CI workflow (.github/workflows/ci.yml)
# It can still run independently for style-only checks

on:
  workflow_dispatch:  # Allow manual trigger
  workflow_call:      # Allow being called from other workflows

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install format dependencies
        run: |
          pip3 install clang-format==14.0.6 cmake_format==0.6.11 pyyaml
          sudo apt-get update
          sudo apt-get install -y libboost-all-dev

      - name: Check C++ formatting
        run: |
          echo "Checking C++ code formatting..."
          find include source standalone test -name "*.cpp" -o -name "*.hpp" | \
          xargs clang-format --dry-run --Werror 2>&1 | tee format_check.log || true
          if grep -q "error:" format_check.log; then
            echo "::error::C++ formatting issues found. Run 'clang-format -i' on affected files."
            cat format_check.log
            exit 1
          else
            echo "C++ formatting check passed!"
          fi

      - name: Check CMake formatting
        run: |
          find . -name "CMakeLists.txt" -o -name "*.cmake" | \
          grep -v build | grep -v cpm_modules | \
          xargs cmake-format --check 2>&1 | tee cmake_format_check.log
          if grep -q "would be reformatted" cmake_format_check.log; then
            echo "CMake formatting issues found!"
            exit 1
          fi