name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Boost
      uses: MarkusJx/install-boost@v2.4.5
      id: install-boost
      with:
        boost_version: 1.83.0
        platform_version: 2022
        toolset: msvc
        
    - name: Configure CMake
      run: |
        cmake -B build -S . `
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} `
          -DBoost_ROOT=${{ steps.install-boost.outputs.BOOST_ROOT }}
      
    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }} -j
      
    - name: Run unit tests
      working-directory: build/test
      shell: cmd
      run: |
        for %%f in (test_*.exe) do (
          echo Running %%f...
          %%f
        )
        
    - name: Setup Python for Robot tests
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install Robot Framework
      run: |
        pip install robotframework==7.0 pexpect==4.9.0 psutil==5.9.8
        
    - name: Run Robot Framework tests  
      run: |
        robot --variable CLI_PATH:${{ github.workspace }}\build\standalone\liarsdice.exe `
              --outputdir test\robot\results `
              test\robot\liarsdice_tests.robot
              
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: robot-results-windows-${{ matrix.build_type }}
        path: test/robot/results/